<?php
/**
 * @file
 * dcco_landing_promo.context.inc
 */

/**
 * Implements hook_context_default_contexts().
 */
function dcco_landing_promo_context_default_contexts() {
  $export = array();

  $context = new stdClass();
  $context->disabled = FALSE; /* Edit this to true to make a default context disabled initially */
  $context->api_version = 3;
  $context->name = 'promo';
  $context->description = 'Landing page promo block placement';
  $context->tag = 'global';
  $context->conditions = array(
    'path' => array(
      'values' => array(
        '<front>' => '<front>',
      ),
    ),
  );
  $context->reactions = array(
    'block' => array(
      'blocks' => array(
        'views-promo-block' => array(
          'module' => 'views',
          'delta' => 'promo-block',
          'region' => 'above_content',
          'weight' => '-10',
        ),
      ),
    ),
  );
  $context->condition_mode = 0;

  // Translatables
  // Included for use with string extractors like potx.
  t('Landing page promo block placement');
  t('global');
  $export['promo'] = $context;

  return $export;
}
